"""Fail-closed raw-decision contract for M3 behavior calibration.

The records defined here are deliberately *not* calibration evidence.  They
bind an observed T1/T2 action to the exact public/private information available
to the actor, while keeping root commitments, worker seeds, and any full hidden
trace outside the policy input.  Every derived action field is regenerated by
the verifier from :class:`BehaviorInfoSet` and the canonical action engine.

Passing this verifier only means that raw logging is internally consistent.
Both records and manifests remain ``promotion_eligible=false`` until a separate
locked-test calibration gate is implemented and passed.
"""
from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from dataclasses import dataclass
from fractions import Fraction
from typing import Any, Iterable, Mapping, Sequence

from ai.engine.action_space import Action, get_semantic_action_index, get_turn_actions
from ai.engine.encoding import ALL_CARDS, Board
from ai.engine.turn_order import (
    POSITION_CONTRACT_VERSION,
    validate_decision_board_counts,
)
from ai.tutor.exact_late import action_key
from ai.tutor.t3_hu_full_card_range import BehaviorInfoSet
from ai.tutor.t3_hu_public_cfr import PrivateRecall


DECISION_LOG_SCHEMA = "ofc_behavior_decision_log/v1"
MANIFEST_SCHEMA = "ofc_behavior_decision_manifest/v1"
SPLIT_NAMESPACE = "behavior-cal-v1"
SPLIT_NAMES = ("fit", "dev", "test")
JOKER_IDS = ("X1", "X2")
RULES_VERSION = "canonical_joker_bottom_middle_top_20260711"

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_ROWS = ("top", "middle", "bottom")
_VALID_CARDS = frozenset(ALL_CARDS)
_FORBIDDEN_POLICY_KEYS = frozenset(
    {
        "hidden_full_trace",
        "full_private_trace",
        "opponent_private",
        "opponent_discards",
        "opponent_private_discards",
        "undealt",
        "undealt_cards",
        "remaining_deck",
        "live_cards",
        "root_id",
        "root_commitment",
        "seed",
        "seed_namespace",
        "rng_seed",
        "world_id",
        "particle_id",
        "determinization_id",
        "observed_action_key",
        "observed_discard",
        "observed_semantic_index",
        "source_action_probability",
    }
)

_INFORMATION_KEYS = frozenset(
    {
        "position_contract_version",
        "actor",
        "turn",
        "board_bb",
        "board_btn",
        "public_action_history",
        "own_recall_before",
        "current_draw",
        "legal_action_ids",
        "fantasy_state",
    }
)
_RECORD_KEYS = frozenset(
    {
        "schema",
        "promotion_eligible",
        "root_id",
        "root_commitment",
        "seed_namespace",
        "behavior_target_id",
        "policy_sha256",
        "sampling_contract",
        "rules",
        "split",
        "split_bucket",
        "decision_id",
        "turn",
        "actor",
        "information",
        "information_digest",
        "current_draw",
        "observed_action_key",
        "observed_discard",
        "observed_semantic_index",
        "legal_action_ids",
        "mask27",
        "source_action_probability",
        "visible_joker_count",
        "record_sha256",
    }
)


def _rules_contract() -> dict[str, Any]:
    return {
        "rules_version": RULES_VERSION,
        "variant": "standard_ofc_pineapple_hu",
        "normal_hand_only": True,
        "deck_size": 54,
        "physical_joker_ids": ["X1", "X2"],
        "joker_identity_contract": "distinct_physical_X1_X2",
        "position_contract_version": POSITION_CONTRACT_VERSION,
        "action_order": "bb_first_every_turn",
        "logged_turns": [1, 2],
        "regular_action_space": "discard_3_x_row_3_x_row_3_semantic_27",
    }


def _validate_json_value(value: Any, *, path: str = "value") -> None:
    """Reject values whose JSON representation is lossy or non-portable."""
    if value is None or isinstance(value, (str, bool, int)):
        return
    if isinstance(value, float):
        raise TypeError(f"{path} must not contain binary floats")
    if isinstance(value, list):
        for index, item in enumerate(value):
            _validate_json_value(item, path=f"{path}[{index}]")
        return
    if isinstance(value, dict):
        for key, item in value.items():
            if not isinstance(key, str):
                raise TypeError(f"{path} has a non-string JSON key: {key!r}")
            _validate_json_value(item, path=f"{path}.{key}")
        return
    raise TypeError(f"{path} contains unsupported JSON value {type(value).__name__}")


def canonical_json(value: Any) -> str:
    """Return deterministic UTF-8 JSON text for a contract value."""
    _validate_json_value(value)
    return json.dumps(
        value,
        ensure_ascii=False,
        allow_nan=False,
        sort_keys=True,
        separators=(",", ":"),
    )


def canonical_sha256(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def canonical_snapshot(value: Any) -> Any:
    return json.loads(canonical_json(value))


def commit_hidden_root_trace(hidden_full_trace: Any) -> str:
    """Commit a full root trace without adding it to the policy information.

    A collector may retain the preimage in a separately access-controlled raw
    artifact.  Decision records contain only this digest.
    """
    return canonical_sha256(hidden_full_trace)


def _require_mapping(value: Any, *, label: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise TypeError(f"{label} must be an object")
    return value


def _require_exact_keys(
    value: Mapping[str, Any], expected: frozenset[str], *, label: str
) -> None:
    actual = frozenset(value)
    missing = sorted(expected - actual)
    extra = sorted(actual - expected)
    if missing or extra:
        raise ValueError(f"{label} keys mismatch: missing={missing}, extra={extra}")


def _require_nonempty_string(value: Any, *, label: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{label} must be a non-empty string")
    return value


def _require_sha256(value: Any, *, label: str) -> str:
    if not isinstance(value, str) or not _SHA256_RE.fullmatch(value):
        raise ValueError(f"{label} must be a lowercase SHA-256")
    return value


def _fraction(value: Fraction | int | str, *, label: str) -> Fraction:
    if isinstance(value, (bool, float)):
        raise TypeError(f"{label} must be an exact Fraction/int/str")
    try:
        result = value if isinstance(value, Fraction) else Fraction(value)
    except (TypeError, ValueError, ZeroDivisionError) as exc:
        raise TypeError(f"{label} is not an exact rational") from exc
    return result


def _fraction_text(value: Fraction | int | str, *, label: str) -> str:
    result = _fraction(value, label=label)
    return f"{result.numerator}/{result.denominator}"


def root_split_bucket(root_id: str) -> int:
    """Map a root to its immutable fit/dev/test bucket before labels are seen."""
    root = _require_nonempty_string(root_id, label="root_id")
    digest = hashlib.sha256((SPLIT_NAMESPACE + root).encode("utf-8")).digest()
    return int.from_bytes(digest[:8], byteorder="big", signed=False) % 10_000


def root_split(root_id: str) -> str:
    bucket = root_split_bucket(root_id)
    if bucket < 7_000:
        return "fit"
    if bucket < 8_500:
        return "dev"
    return "test"


def _decision_id(root_id: str, *, turn: int, actor: str) -> str:
    return canonical_sha256(
        {
            "schema": "ofc_behavior_decision_identity/v1",
            "root_id": root_id,
            "turn": turn,
            "actor": actor,
        }
    )


def _parse_rows(value: Any, *, label: str) -> tuple[tuple[str, ...], ...]:
    board = _require_mapping(value, label=label)
    _require_exact_keys(board, frozenset(_ROWS), label=label)
    rows: list[tuple[str, ...]] = []
    for row in _ROWS:
        cards = board[row]
        if not isinstance(cards, list):
            raise TypeError(f"{label}.{row} must be a list")
        if any(not isinstance(card, str) or card not in _VALID_CARDS for card in cards):
            raise ValueError(f"{label}.{row} contains an invalid physical card")
        if len(cards) != len(set(cards)):
            raise ValueError(f"{label}.{row} contains duplicate cards")
        if cards != sorted(cards):
            raise ValueError(f"{label}.{row} must be canonically sorted")
        rows.append(tuple(cards))
    return tuple(rows)


def _parse_public_history(value: Any) -> tuple[Any, ...]:
    if not isinstance(value, list):
        raise TypeError("information.public_action_history must be a list")
    history: list[Any] = []
    for index, raw_entry in enumerate(value):
        entry = _require_mapping(raw_entry, label=f"public_action_history[{index}]")
        _require_exact_keys(
            entry,
            frozenset({"turn", "actor", "placements"}),
            label=f"public_action_history[{index}]",
        )
        if isinstance(entry["turn"], bool) or not isinstance(entry["turn"], int):
            raise TypeError("public history turn must be an integer")
        actor = entry["actor"]
        if actor not in ("bb", "btn"):
            raise ValueError("public history actor must be bb or btn")
        raw_placements = entry["placements"]
        if not isinstance(raw_placements, list):
            raise TypeError("public history placements must be a list")
        placements: list[tuple[str, str]] = []
        for raw in raw_placements:
            if not isinstance(raw, list) or len(raw) != 2:
                raise ValueError("public history placement must be [card,row]")
            card, row = raw
            if not isinstance(card, str) or card not in _VALID_CARDS:
                raise ValueError("public history contains an invalid physical card")
            if row not in _ROWS:
                raise ValueError("public history contains an invalid row")
            placements.append((card, row))
        canonical = sorted(placements, key=lambda item: (item[1], item[0]))
        if placements != canonical:
            raise ValueError("public history placements must be canonically sorted")
        history.append((entry["turn"], actor, tuple(placements)))
    return tuple(history)


def _parse_recall(value: Any) -> PrivateRecall:
    recall = _require_mapping(value, label="information.own_recall_before")
    _require_exact_keys(
        recall,
        frozenset({"dealt_by_turn", "discards_by_turn"}),
        label="information.own_recall_before",
    )
    dealt_raw = recall["dealt_by_turn"]
    discard_raw = recall["discards_by_turn"]
    if not isinstance(dealt_raw, list) or not isinstance(discard_raw, list):
        raise TypeError("private recall lists are required")
    dealt: list[tuple[int, tuple[str, ...]]] = []
    for index, raw in enumerate(dealt_raw):
        item = _require_mapping(raw, label=f"dealt_by_turn[{index}]")
        _require_exact_keys(
            item,
            frozenset({"turn", "cards"}),
            label=f"dealt_by_turn[{index}]",
        )
        if isinstance(item["turn"], bool) or not isinstance(item["turn"], int):
            raise TypeError("private recall turn must be an integer")
        if not isinstance(item["cards"], list):
            raise TypeError("private recall cards must be a list")
        dealt.append((item["turn"], tuple(item["cards"])))
    discards: list[tuple[int, str]] = []
    for index, raw in enumerate(discard_raw):
        item = _require_mapping(raw, label=f"discards_by_turn[{index}]")
        _require_exact_keys(
            item,
            frozenset({"turn", "card"}),
            label=f"discards_by_turn[{index}]",
        )
        if isinstance(item["turn"], bool) or not isinstance(item["turn"], int):
            raise TypeError("private discard turn must be an integer")
        if not isinstance(item["card"], str):
            raise TypeError("private discard card must be a string")
        discards.append((item["turn"], item["card"]))
    return PrivateRecall(tuple(dealt), tuple(discards))


def _walk_keys(value: Any) -> Iterable[str]:
    if isinstance(value, Mapping):
        for key, item in value.items():
            yield str(key).lower()
            yield from _walk_keys(item)
    elif isinstance(value, (list, tuple)):
        for item in value:
            yield from _walk_keys(item)


def _reconstruct_information(payload: Any) -> BehaviorInfoSet:
    raw = _require_mapping(payload, label="information")
    _require_exact_keys(raw, _INFORMATION_KEYS, label="information")
    leaked = sorted(set(_walk_keys(raw)) & _FORBIDDEN_POLICY_KEYS)
    if leaked:
        raise ValueError(f"information contains forbidden hidden/label fields: {leaked}")
    if raw["position_contract_version"] != POSITION_CONTRACT_VERSION:
        raise ValueError("information position contract must be bb_first_v1")
    actor = raw["actor"]
    if actor not in ("bb", "btn"):
        raise ValueError("information actor must be bb or btn")
    turn = raw["turn"]
    if isinstance(turn, bool) or turn not in (1, 2):
        raise ValueError("behavior calibration log supports only T1/T2")
    if raw["fantasy_state"] is not None:
        raise ValueError("behavior calibration v1 supports normal hands only")
    current_draw = raw["current_draw"]
    legal_action_ids = raw["legal_action_ids"]
    if not isinstance(current_draw, list) or len(current_draw) != 3:
        raise ValueError("information current_draw must contain exactly three cards")
    if any(not isinstance(card, str) or card not in _VALID_CARDS for card in current_draw):
        raise ValueError("information current_draw contains an invalid physical card")
    if len(current_draw) != len(set(current_draw)):
        raise ValueError("information current_draw contains duplicate cards")
    if current_draw != sorted(current_draw):
        raise ValueError("information current_draw must be canonically sorted")
    if not isinstance(legal_action_ids, list) or any(
        not isinstance(item, str) for item in legal_action_ids
    ):
        raise TypeError("information legal_action_ids must be a string list")

    information = BehaviorInfoSet(
        actor=actor,
        turn=turn,
        board_bb=_parse_rows(raw["board_bb"], label="information.board_bb"),  # type: ignore[arg-type]
        board_btn=_parse_rows(raw["board_btn"], label="information.board_btn"),  # type: ignore[arg-type]
        public_action_history=_parse_public_history(raw["public_action_history"]),
        own_recall_before=_parse_recall(raw["own_recall_before"]),
        current_draw=tuple(current_draw),
        legal_action_ids=tuple(legal_action_ids),
        fantasy_state=None,
    )
    if information.to_canonical_dict() != raw:
        raise ValueError("information is not the canonical BehaviorInfoSet payload")
    _validate_information_cutoff(information)
    return information


def _validate_information_cutoff(information: BehaviorInfoSet) -> None:
    """Independently enforce T1/T2 BB-first public and private cutoffs."""
    actor = information.actor
    turn = information.turn
    hero = information.board_bb if actor == "bb" else information.board_btn
    opponent = information.board_btn if actor == "bb" else information.board_bb
    validate_decision_board_counts(
        turn,
        actor,
        sum(map(len, hero)),
        sum(map(len, opponent)),
    )
    for label, rows in (("BB", information.board_bb), ("BTN", information.board_btn)):
        if any(len(row) > limit for row, limit in zip(rows, (3, 5, 5))):
            raise ValueError(f"{label} board exceeds row capacity")

    expected_pairs: list[tuple[int, str]] = [(0, "bb"), (0, "btn")]
    for prior_turn in range(1, turn):
        expected_pairs.extend(((prior_turn, "bb"), (prior_turn, "btn")))
    if actor == "btn":
        expected_pairs.append((turn, "bb"))
    actual_pairs = [
        (history_turn, history_actor)
        for history_turn, history_actor, _placements in information.public_action_history
    ]
    if actual_pairs != expected_pairs:
        raise ValueError(
            f"T{turn} {actor} requires BB-first history {expected_pairs}, got {actual_pairs}"
        )

    reconstructed = {
        "bb": {row: [] for row in _ROWS},
        "btn": {row: [] for row in _ROWS},
    }
    seen_public: set[str] = set()
    public_by_actor_turn: dict[tuple[str, int], set[str]] = {}
    for history_turn, history_actor, placements in information.public_action_history:
        expected_count = 5 if history_turn == 0 else 2
        if len(placements) != expected_count:
            raise ValueError(
                f"T{history_turn} {history_actor} requires {expected_count} placements"
            )
        cards = {card for card, _row in placements}
        if len(cards) != len(placements) or seen_public.intersection(cards):
            raise ValueError("public history contains a duplicate physical card")
        seen_public.update(cards)
        public_by_actor_turn[(history_actor, history_turn)] = cards
        for card, row in placements:
            reconstructed[history_actor][row].append(card)
    for board_actor, rows in (("bb", information.board_bb), ("btn", information.board_btn)):
        expected_rows = tuple(
            tuple(sorted(reconstructed[board_actor][row])) for row in _ROWS
        )
        if rows != expected_rows:
            raise ValueError(f"{board_actor.upper()} board does not match public history")

    recall = information.own_recall_before
    expected_recall_turns = tuple(range(1, turn))
    dealt_turns = tuple(item_turn for item_turn, _cards in recall.dealt_by_turn)
    discard_turns = tuple(item_turn for item_turn, _card in recall.discards_by_turn)
    if dealt_turns != expected_recall_turns or discard_turns != expected_recall_turns:
        raise ValueError(
            f"T{turn} recall must contain completed turns {expected_recall_turns}"
        )
    discards = dict(recall.discards_by_turn)
    remembered: set[str] = set()
    for prior_turn, cards in recall.dealt_by_turn:
        if len(cards) != 3:
            raise ValueError("each prior private draw must contain three cards")
        expected = public_by_actor_turn[(actor, prior_turn)] | {discards[prior_turn]}
        if set(cards) != expected:
            raise ValueError("private recall must equal own placements plus own discard")
        remembered.update(cards)
    if set(discards.values()) & seen_public:
        raise ValueError("own private discard appears in public history")
    current = set(information.current_draw)
    if current & (seen_public | remembered):
        raise ValueError("current draw overlaps public or remembered cards")


def _derived_actions(
    information: BehaviorInfoSet,
) -> tuple[dict[str, Action], tuple[str, ...], tuple[bool, ...]]:
    rows = information.board_bb if information.actor == "bb" else information.board_btn
    board = Board(top=list(rows[0]), middle=list(rows[1]), bottom=list(rows[2]))
    legal = get_turn_actions(list(information.current_draw), board)
    by_id = {action_key(action): action for action in legal}
    if len(by_id) != len(legal):
        raise AssertionError("canonical action engine generated duplicate action IDs")
    action_ids = tuple(sorted(by_id))
    mask = [False] * 27
    seen_indices: set[int] = set()
    for action in legal:
        index = get_semantic_action_index(action, list(information.current_draw))
        if not 0 <= index < 27 or index in seen_indices:
            raise AssertionError("canonical action engine generated invalid semantic indices")
        seen_indices.add(index)
        mask[index] = True
    return by_id, action_ids, tuple(mask)


def build_behavior_decision_log(
    *,
    root_id: str,
    root_commitment: str,
    seed_namespace: str,
    behavior_target_id: str,
    policy_sha256: str,
    sampling_contract: str | Mapping[str, Any],
    information: BehaviorInfoSet,
    observed_action_key: str,
    source_action_probability: Fraction | int | str,
) -> dict[str, Any]:
    """Build and self-verify one canonical T1/T2 behavior decision record."""
    root = _require_nonempty_string(root_id, label="root_id")
    _require_sha256(root_commitment, label="root_commitment")
    _require_nonempty_string(seed_namespace, label="seed_namespace")
    _require_nonempty_string(behavior_target_id, label="behavior_target_id")
    _require_sha256(policy_sha256, label="policy_sha256")
    if not isinstance(sampling_contract, (str, Mapping)):
        raise TypeError("sampling_contract must be a string or object")
    sampling = canonical_snapshot(
        dict(sampling_contract) if isinstance(sampling_contract, Mapping) else sampling_contract
    )
    if sampling in ("", {}):
        raise ValueError("sampling_contract must not be empty")
    if not isinstance(information, BehaviorInfoSet):
        raise TypeError("information must be a BehaviorInfoSet")

    information_payload = information.to_canonical_dict()
    reconstructed = _reconstruct_information(information_payload)
    by_id, legal_ids, mask = _derived_actions(reconstructed)
    if reconstructed.legal_action_ids != legal_ids:
        raise ValueError("BehaviorInfoSet legal action IDs do not match the action engine")
    observed_key = _require_nonempty_string(
        observed_action_key, label="observed_action_key"
    )
    if observed_key not in by_id:
        raise ValueError("observed action is not legal for the BehaviorInfoSet")
    observed = by_id[observed_key]
    semantic_index = get_semantic_action_index(
        observed, list(reconstructed.current_draw)
    )
    probability = _fraction(source_action_probability, label="source_action_probability")
    if not Fraction(0) < probability <= Fraction(1):
        raise ValueError("source_action_probability must be in (0,1]")
    split = root_split(root)
    bucket = root_split_bucket(root)
    record: dict[str, Any] = {
        "schema": DECISION_LOG_SCHEMA,
        "promotion_eligible": False,
        "root_id": root,
        "root_commitment": root_commitment,
        "seed_namespace": seed_namespace,
        "behavior_target_id": behavior_target_id,
        "policy_sha256": policy_sha256,
        "sampling_contract": sampling,
        "rules": _rules_contract(),
        "split": split,
        "split_bucket": bucket,
        "decision_id": _decision_id(root, turn=reconstructed.turn, actor=reconstructed.actor),
        "turn": reconstructed.turn,
        "actor": reconstructed.actor,
        "information": information_payload,
        "information_digest": reconstructed.digest(),
        "current_draw": list(reconstructed.current_draw),
        "observed_action_key": observed_key,
        "observed_discard": observed.discard,
        "observed_semantic_index": semantic_index,
        "legal_action_ids": list(legal_ids),
        "mask27": list(mask),
        "source_action_probability": _fraction_text(
            probability, label="source_action_probability"
        ),
        "visible_joker_count": sum(card in JOKER_IDS for card in reconstructed.current_draw),
    }
    record["record_sha256"] = canonical_sha256(record)
    verify_behavior_decision_log(record)
    return record


@dataclass(frozen=True)
class VerifiedBehaviorDecision:
    record_sha256: str
    decision_id: str
    root_id: str
    root_commitment: str
    seed_namespace: str
    behavior_target_id: str
    policy_sha256: str
    split: str
    split_bucket: int
    turn: int
    actor: str
    visible_joker_count: int
    information: BehaviorInfoSet
    observed_action: Action
    source_action_probability: Fraction


def verify_behavior_decision_log(record: Mapping[str, Any]) -> VerifiedBehaviorDecision:
    """Independently reconstruct and validate one content-bound raw record."""
    raw = _require_mapping(record, label="behavior decision record")
    _require_exact_keys(raw, _RECORD_KEYS, label="behavior decision record")
    if raw["schema"] != DECISION_LOG_SCHEMA:
        raise ValueError("unsupported behavior decision schema")
    if raw["promotion_eligible"] is not False:
        raise ValueError("raw behavior records are never promotion eligible")
    recorded_sha = _require_sha256(raw["record_sha256"], label="record_sha256")
    unsigned = dict(raw)
    unsigned.pop("record_sha256")
    if canonical_sha256(unsigned) != recorded_sha:
        raise ValueError("behavior decision record SHA-256 mismatch")

    root = _require_nonempty_string(raw["root_id"], label="root_id")
    root_commitment = _require_sha256(
        raw["root_commitment"], label="root_commitment"
    )
    seed_namespace = _require_nonempty_string(
        raw["seed_namespace"], label="seed_namespace"
    )
    behavior_target_id = _require_nonempty_string(
        raw["behavior_target_id"], label="behavior_target_id"
    )
    policy_sha256 = _require_sha256(raw["policy_sha256"], label="policy_sha256")
    if raw["rules"] != _rules_contract():
        raise ValueError("behavior decision rules contract mismatch")
    sampling = canonical_snapshot(raw["sampling_contract"])
    if sampling in ("", {}):
        raise ValueError("sampling_contract must not be empty")

    expected_split = root_split(root)
    expected_bucket = root_split_bucket(root)
    if raw["split"] != expected_split or raw["split_bucket"] != expected_bucket:
        raise ValueError("root-hash split mismatch")

    information = _reconstruct_information(raw["information"])
    if raw["actor"] != information.actor or raw["turn"] != information.turn:
        raise ValueError("record actor/turn does not match information")
    if raw["information_digest"] != information.digest():
        raise ValueError("information digest mismatch")
    if raw["current_draw"] != list(information.current_draw):
        raise ValueError("record current_draw does not match information")

    by_id, legal_ids, mask = _derived_actions(information)
    if information.legal_action_ids != legal_ids:
        raise ValueError("information legal action IDs do not match independent derivation")
    if raw["legal_action_ids"] != list(legal_ids):
        raise ValueError("record legal action IDs do not match independent derivation")
    raw_mask = raw["mask27"]
    if (
        not isinstance(raw_mask, list)
        or len(raw_mask) != 27
        or any(type(item) is not bool for item in raw_mask)
        or raw_mask != list(mask)
    ):
        raise ValueError("record mask27 does not match independent derivation")

    observed_key = raw["observed_action_key"]
    if not isinstance(observed_key, str) or observed_key not in by_id:
        raise ValueError("observed action key is not independently legal")
    observed = by_id[observed_key]
    if action_key(observed) != observed_key:
        raise AssertionError("action key roundtrip failed")
    if raw["observed_discard"] != observed.discard:
        raise ValueError("observed discard does not match observed action")
    semantic_index = get_semantic_action_index(observed, list(information.current_draw))
    if (
        isinstance(raw["observed_semantic_index"], bool)
        or raw["observed_semantic_index"] != semantic_index
    ):
        raise ValueError("observed semantic index does not match observed action")
    if not mask[semantic_index]:
        raise AssertionError("observed semantic index is absent from the legal mask")

    probability_text = raw["source_action_probability"]
    if not isinstance(probability_text, str):
        raise TypeError("source_action_probability must be a canonical rational string")
    probability = _fraction(probability_text, label="source_action_probability")
    if probability_text != _fraction_text(
        probability, label="source_action_probability"
    ):
        raise ValueError("source_action_probability is not canonical")
    if not Fraction(0) < probability <= Fraction(1):
        raise ValueError("source_action_probability must be in (0,1]")

    joker_count = sum(card in JOKER_IDS for card in information.current_draw)
    if raw["visible_joker_count"] != joker_count:
        raise ValueError("visible Joker count does not match current_draw")
    expected_decision_id = _decision_id(
        root, turn=information.turn, actor=information.actor
    )
    if raw["decision_id"] != expected_decision_id:
        raise ValueError("decision identity mismatch")

    return VerifiedBehaviorDecision(
        record_sha256=recorded_sha,
        decision_id=expected_decision_id,
        root_id=root,
        root_commitment=root_commitment,
        seed_namespace=seed_namespace,
        behavior_target_id=behavior_target_id,
        policy_sha256=policy_sha256,
        split=expected_split,
        split_bucket=expected_bucket,
        turn=information.turn,
        actor=information.actor,
        visible_joker_count=joker_count,
        information=information,
        observed_action=observed,
        source_action_probability=probability,
    )


def _empty_role_joker_counts() -> dict[str, dict[str, int]]:
    return {
        actor: {f"joker_{joker_count}": 0 for joker_count in range(3)}
        for actor in ("bb", "btn")
    }


def _increment_role_joker(
    counts: dict[str, dict[str, int]], *, actor: str, joker_count: int
) -> None:
    counts[actor][f"joker_{joker_count}"] += 1


def build_behavior_decision_manifest(
    records: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Verify records and bind their split/stratum census into one manifest."""
    if not records:
        raise ValueError("behavior calibration dataset is empty; collection cannot pass")
    verified = [verify_behavior_decision_log(record) for record in records]

    decision_ids: set[str] = set()
    decision_keys: set[tuple[str, int, str]] = set()
    root_contract: dict[str, tuple[str, str, str]] = {}
    for item in verified:
        decision_key = (item.root_id, item.turn, item.actor)
        if item.decision_id in decision_ids or decision_key in decision_keys:
            raise ValueError(f"duplicate behavior decision: {decision_key}")
        decision_ids.add(item.decision_id)
        decision_keys.add(decision_key)
        contract = (
            item.root_commitment,
            item.seed_namespace,
            item.split,
        )
        prior = root_contract.setdefault(item.root_id, contract)
        if prior != contract:
            raise ValueError("one root has inconsistent commitment/seed/split metadata")

    target_ids = {item.behavior_target_id for item in verified}
    policy_hashes = {item.policy_sha256 for item in verified}
    sampling_contracts = {
        canonical_json(record["sampling_contract"]) for record in records
    }
    if len(target_ids) != 1 or len(policy_hashes) != 1:
        raise ValueError("one manifest cannot mix behavior targets or policy hashes")
    if len(sampling_contracts) != 1:
        raise ValueError("one manifest cannot mix sampling contracts")

    roots_by_split: dict[str, set[str]] = {name: set() for name in SPLIT_NAMES}
    decisions_by_split: Counter[str] = Counter()
    role_joker_counts = _empty_role_joker_counts()
    split_role_joker_counts = {
        split: _empty_role_joker_counts() for split in SPLIT_NAMES
    }
    turn_role_joker_counts = {
        f"t{turn}": _empty_role_joker_counts() for turn in (1, 2)
    }
    turn_actor_counts = {
        f"t{turn}": {actor: 0 for actor in ("bb", "btn")} for turn in (1, 2)
    }
    legal_count_histogram: dict[str, Counter[str]] = {
        actor: Counter() for actor in ("bb", "btn")
    }
    for item in verified:
        roots_by_split[item.split].add(item.root_id)
        decisions_by_split[item.split] += 1
        _increment_role_joker(
            role_joker_counts,
            actor=item.actor,
            joker_count=item.visible_joker_count,
        )
        _increment_role_joker(
            split_role_joker_counts[item.split],
            actor=item.actor,
            joker_count=item.visible_joker_count,
        )
        _increment_role_joker(
            turn_role_joker_counts[f"t{item.turn}"],
            actor=item.actor,
            joker_count=item.visible_joker_count,
        )
        turn_actor_counts[f"t{item.turn}"][item.actor] += 1
        legal_count_histogram[item.actor][
            str(item.information.legal_action_count)
        ] += 1

    intersections = {
        "fit_dev": len(roots_by_split["fit"] & roots_by_split["dev"]),
        "fit_test": len(roots_by_split["fit"] & roots_by_split["test"]),
        "dev_test": len(roots_by_split["dev"] & roots_by_split["test"]),
    }
    if any(intersections.values()):
        raise ValueError("root overlap across calibration splits")

    record_hashes = sorted(item.record_sha256 for item in verified)
    manifest: dict[str, Any] = {
        "schema": MANIFEST_SCHEMA,
        "promotion_eligible": False,
        "calibration_gate_status": "not_evaluated",
        "raw_records_verified": True,
        "record_count": len(verified),
        "root_count": len(root_contract),
        "behavior_target_id": next(iter(target_ids)),
        "policy_sha256": next(iter(policy_hashes)),
        "sampling_contract": canonical_snapshot(records[0]["sampling_contract"]),
        "sampling_contract_sha256": canonical_sha256(records[0]["sampling_contract"]),
        "rules": _rules_contract(),
        "rules_sha256": canonical_sha256(_rules_contract()),
        "split_contract": {
            "namespace": SPLIT_NAMESPACE,
            "hash": "sha256(namespace_utf8 || root_id_utf8)",
            "bucket": "uint64_be(first_8_digest_bytes) % 10000",
            "fit": [0, 6999],
            "dev": [7000, 8499],
            "test": [8500, 9999],
        },
        "decision_counts_by_split": {
            name: decisions_by_split[name] for name in SPLIT_NAMES
        },
        "root_counts_by_split": {
            name: len(roots_by_split[name]) for name in SPLIT_NAMES
        },
        "root_list_commitments_by_split": {
            name: canonical_sha256(sorted(roots_by_split[name])) for name in SPLIT_NAMES
        },
        "root_overlap_audit": {
            "checked": True,
            "pairwise_overlap_counts": intersections,
            "overlap_count": sum(intersections.values()),
        },
        "duplicate_decision_count": 0,
        "role_joker_counts": role_joker_counts,
        "split_role_joker_counts": split_role_joker_counts,
        "turn_role_joker_counts": turn_role_joker_counts,
        "turn_actor_counts": turn_actor_counts,
        "legal_action_count_histogram_by_actor": {
            actor: dict(sorted(histogram.items(), key=lambda item: int(item[0])))
            for actor, histogram in legal_count_histogram.items()
        },
        "seed_namespaces": sorted({item.seed_namespace for item in verified}),
        "record_set_sha256": canonical_sha256(record_hashes),
        "decision_identity_set_sha256": canonical_sha256(sorted(decision_ids)),
        "information_contract": {
            "schema": "BehaviorInfoSet.canonical_payload",
            "hidden_full_trace_in_policy_input": False,
            "root_metadata_in_policy_input": False,
            "observed_label_in_policy_input": False,
        },
    }
    manifest["manifest_sha256"] = canonical_sha256(manifest)
    return manifest


def verify_behavior_decision_dataset(
    records: Sequence[Mapping[str, Any]],
    manifest: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Rebuild a manifest; optionally require byte-semantic equality to one supplied."""
    rebuilt = build_behavior_decision_manifest(records)
    if manifest is not None:
        supplied = _require_mapping(manifest, label="behavior decision manifest")
        supplied_hash = _require_sha256(
            supplied.get("manifest_sha256"), label="manifest_sha256"
        )
        unsigned = dict(supplied)
        unsigned.pop("manifest_sha256", None)
        if canonical_sha256(unsigned) != supplied_hash:
            raise ValueError("behavior decision manifest SHA-256 mismatch")
        if canonical_snapshot(supplied) != rebuilt:
            raise ValueError("behavior decision manifest does not match raw records")
    return rebuilt


__all__ = [
    "DECISION_LOG_SCHEMA",
    "MANIFEST_SCHEMA",
    "SPLIT_NAMESPACE",
    "VerifiedBehaviorDecision",
    "build_behavior_decision_log",
    "build_behavior_decision_manifest",
    "canonical_json",
    "canonical_sha256",
    "commit_hidden_root_trace",
    "root_split",
    "root_split_bucket",
    "verify_behavior_decision_dataset",
    "verify_behavior_decision_log",
]
