"""3-max (three-player) regular OFC Pineapple core.

Rules are frozen in ``docs/three_max_rules_contract_20260812.md``.  This package
is parallel to the heads-up stack, never a widening of it: the HU observation
schema, geometry tables, validators, and weights stay exactly as they are.
"""

from .exact import (
    ExactCandidate,
    T3Candidate,
    evaluate_t3,
    evaluate_t4_exact,
    exact_t4_policy,
)
from .features import FEATURE_SIZE, EncodedAction, encode, encode_record_action
from .interior import (
    MiddleDraw,
    evaluate_t3_middle,
    exact_interior,
    mc_interior,
    model_interior,
    random_interior,
    sample_middle_draws,
)
from .mc import McCandidate, evaluate_actions_mc, mc_policy
from .play import (
    HandResult3,
    Policy3,
    SessionHand,
    decision_seed,
    play_hand,
    play_session,
    uniform_random_policy,
)
from .scoring import (
    DEFAULT_FL_EV_PER_PAIR,
    HandSettlement,
    OPPONENTS_PER_PLAYER,
    PairSettlement,
    fl_ev_hand_total,
    load_fl_ev_3max,
    pair_scores,
    settle_hand,
)
from .seating import (
    ACT_ORDER,
    CARDS_DEALT_PER_HAND,
    DEAL_SCHEDULE,
    DECISION_GEOMETRY,
    DECISIONS_PER_HAND,
    PLAYER_COUNT,
    SEAT_BTN,
    SEAT_SB,
    SEAT_BB,
    SETTLEMENT_ORDER,
    STREETS,
    DealSlot,
    Seat3,
    SeatMap,
    Street3,
    act_order_of,
    geometry_for,
    opponent_seats,
    placement_split,
    player_of_seat,
    rotate_button,
    seat_of_player,
)
from .situations import (
    FANTASYLAND_CARDS,
    FantasylandDeal,
    Reduction,
    StreetSlot,
    TableConfig,
    all_configs,
    deal_plan,
    hero_unseen_count,
    reduction_of,
    situation_summary,
    street_decision_count,
    street_geometry,
)
from .rotation import (
    BlockResult,
    Orientations,
    MatchupSummary,
    ROTATIONS,
    evaluate_matchup,
    play_block,
    seat_for,
    seatings_for,
    self_test,
)
from .world import ThreeMaxObservation, WorldState3

__all__ = [
    "ACT_ORDER",
    "CARDS_DEALT_PER_HAND",
    "DEAL_SCHEDULE",
    "DECISIONS_PER_HAND",
    "DECISION_GEOMETRY",
    "DEFAULT_FL_EV_PER_PAIR",
    "BlockResult",
    "DealSlot",
    "EncodedAction",
    "FEATURE_SIZE",
    "ExactCandidate",
    "HandResult3",
    "HandSettlement",
    "MatchupSummary",
    "McCandidate",
    "MiddleDraw",
    "Orientations",
    "OPPONENTS_PER_PLAYER",
    "PLAYER_COUNT",
    "PairSettlement",
    "ROTATIONS",
    "Policy3",
    "SEAT_BTN",
    "SEAT_SB",
    "SEAT_BB",
    "SeatMap",
    "SETTLEMENT_ORDER",
    "STREETS",
    "Seat3",
    "SessionHand",
    "Street3",
    "ThreeMaxObservation",
    "WorldState3",
    "act_order_of",
    "decision_seed",
    "evaluate_actions_mc",
    "evaluate_matchup",
    "encode",
    "encode_record_action",
    "evaluate_t3",
    "evaluate_t3_middle",
    "evaluate_t4_exact",
    "exact_interior",
    "exact_t4_policy",
    "mc_interior",
    "model_interior",
    "random_interior",
    "sample_middle_draws",
    "fl_ev_hand_total",
    "geometry_for",
    "load_fl_ev_3max",
    "mc_policy",
    "opponent_seats",
    "pair_scores",
    "placement_split",
    "play_block",
    "play_hand",
    "play_session",
    "player_of_seat",
    "rotate_button",
    "seat_for",
    "seat_of_player",
    "seatings_for",
    "self_test",
    "settle_hand",
    "FANTASYLAND_CARDS",
    "FantasylandDeal",
    "Reduction",
    "StreetSlot",
    "T3Candidate",
    "TableConfig",
    "all_configs",
    "deal_plan",
    "hero_unseen_count",
    "reduction_of",
    "situation_summary",
    "street_decision_count",
    "street_geometry",
    "uniform_random_policy",
]
