[package]
name = "t4_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
ofc_core = { path = "../ofc_core" }
fl_solver = { path = "../fl_solver" }
rayon.workspace = true
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
clap.workspace = true
